-- MySQL Script generated by MySQL Workbench
-- Wed Jan 21 23:52:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema barber_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barber_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barber_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `barber_db` ;

-- -----------------------------------------------------
-- Table `barber_db`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`admins` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`businesses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`businesses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(120) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `city` VARCHAR(80) NULL DEFAULT NULL,
  `district` VARCHAR(80) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_businesses_slug` (`slug` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`branches` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `address` VARCHAR(500) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_branches_business` (`business_id` ASC) VISIBLE,
  CONSTRAINT `fk_branches_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `barber_db`.`businesses` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`customers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(20) NOT NULL,
  `display_name` VARCHAR(120) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_customers_phone` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`services` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `duration_minutes` SMALLINT UNSIGNED NOT NULL,
  `price_cents` INT UNSIGNED NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_services_business` (`business_id` ASC) VISIBLE,
  CONSTRAINT `fk_services_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `barber_db`.`businesses` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`staff` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `branch_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `full_name` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_staff_business` (`business_id` ASC) VISIBLE,
  INDEX `idx_staff_branch` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `barber_db`.`branches` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_staff_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `barber_db`.`businesses` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`appointments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `branch_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `staff_id` BIGINT UNSIGNED NOT NULL,
  `service_id` BIGINT UNSIGNED NOT NULL,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `start_at` DATETIME NOT NULL,
  `end_at` DATETIME NOT NULL,
  `status` ENUM('confirmed', 'cancelled', 'no_show', 'completed') NOT NULL DEFAULT 'confirmed',
  `cancelled_by` ENUM('customer', 'staff', 'system') NULL DEFAULT NULL,
  `cancel_reason` VARCHAR(250) NULL DEFAULT NULL,
  `customer_note` VARCHAR(500) NULL DEFAULT NULL,
  `staff_note` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active_lock` TINYINT GENERATED ALWAYS AS ((case when (`status` = _utf8mb4'confirmed') then 1 else NULL end)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_one_active_appt_per_business_customer` (`business_id` ASC, `customer_id` ASC, `active_lock` ASC) VISIBLE,
  INDEX `idx_appt_business_time` (`business_id` ASC, `start_at` ASC) VISIBLE,
  INDEX `idx_appt_staff_time` (`staff_id` ASC, `start_at` ASC) VISIBLE,
  INDEX `idx_appt_customer` (`customer_id` ASC, `start_at` ASC) VISIBLE,
  INDEX `fk_appt_branch` (`branch_id` ASC) VISIBLE,
  INDEX `fk_appt_service` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_appt_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `barber_db`.`branches` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_appt_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `barber_db`.`businesses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_appt_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `barber_db`.`customers` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_appt_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `barber_db`.`services` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_appt_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `barber_db`.`staff` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`appointment_slots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`appointment_slots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `appointment_id` BIGINT UNSIGNED NOT NULL,
  `staff_id` BIGINT UNSIGNED NOT NULL,
  `slot_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_staff_slot` (`staff_id` ASC, `slot_time` ASC) VISIBLE,
  INDEX `idx_slots_appt` (`appointment_id` ASC) VISIBLE,
  CONSTRAINT `fk_slots_appt`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `barber_db`.`appointments` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_slots_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `barber_db`.`staff` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`appointment_status_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`appointment_status_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `appointment_id` BIGINT UNSIGNED NOT NULL,
  `old_status` ENUM('confirmed', 'cancelled', 'no_show', 'completed') NOT NULL,
  `new_status` ENUM('confirmed', 'cancelled', 'no_show', 'completed') NOT NULL,
  `changed_by` ENUM('customer', 'staff', 'system') NOT NULL,
  `note` VARCHAR(250) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_hist_appt` (`appointment_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_hist_appt`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `barber_db`.`appointments` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`branch_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`branch_accounts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `branch_id` BIGINT UNSIGNED NOT NULL,
  `staff_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `last_login_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_branch_account` (`branch_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_branch_account_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `ux_branch_accounts_staff_id` (`staff_id` ASC) VISIBLE,
  INDEX `idx_branch_accounts_business` (`business_id` ASC) VISIBLE,
  CONSTRAINT `fk_branch_account_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `barber_db`.`branches` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_branch_account_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `barber_db`.`businesses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_branch_accounts_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `barber_db`.`staff` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`business_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`business_settings` (
  `business_id` BIGINT UNSIGNED NOT NULL,
  `settings_json` JSON NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`business_id`),
  CONSTRAINT `fk_settings_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `barber_db`.`businesses` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`customer_business_flags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`customer_business_flags` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `no_show_count` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `is_blacklisted` TINYINT(1) NOT NULL DEFAULT '0',
  `blacklisted_at` DATETIME NULL DEFAULT NULL,
  `note` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_flags_business_customer` (`business_id` ASC, `customer_id` ASC) VISIBLE,
  INDEX `idx_flags_blacklist` (`business_id` ASC, `is_blacklisted` ASC) VISIBLE,
  INDEX `fk_flags_customer` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_flags_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `barber_db`.`businesses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_flags_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `barber_db`.`customers` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`otp_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`otp_codes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_type` ENUM('branch_account', 'customer') NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `channel` ENUM('email', 'sms') NOT NULL,
  `destination` VARCHAR(190) NOT NULL,
  `code_hash` CHAR(64) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `used` TINYINT(1) NOT NULL DEFAULT '0',
  `used_at` DATETIME NULL DEFAULT NULL,
  `try_count` INT NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_user_latest` (`user_type` ASC, `user_id` ASC, `id` ASC) VISIBLE,
  INDEX `idx_exp` (`expires_at` ASC) VISIBLE,
  INDEX `idx_used` (`used` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`sms_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`sms_messages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `appointment_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `to_phone` VARCHAR(20) NOT NULL,
  `type` ENUM('reminder', 'otp', 'other') NOT NULL DEFAULT 'reminder',
  `body` VARCHAR(800) NOT NULL,
  `provider` VARCHAR(60) NULL DEFAULT NULL,
  `status` ENUM('queued', 'sent', 'failed', 'cancelled') NOT NULL DEFAULT 'queued',
  `provider_msg_id` VARCHAR(120) NULL DEFAULT NULL,
  `error_message` VARCHAR(300) NULL DEFAULT NULL,
  `scheduled_at` DATETIME NOT NULL,
  `sent_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_sms_queue` (`status` ASC, `scheduled_at` ASC) VISIBLE,
  INDEX `idx_sms_business` (`business_id` ASC, `scheduled_at` ASC) VISIBLE,
  INDEX `fk_sms_appt` (`appointment_id` ASC) VISIBLE,
  CONSTRAINT `fk_sms_appt`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `barber_db`.`appointments` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_sms_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `barber_db`.`businesses` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `barber_db`.`staff_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_db`.`staff_services` (
  `staff_id` BIGINT UNSIGNED NOT NULL,
  `service_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`staff_id`, `service_id`),
  INDEX `idx_staff_services_service` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_services_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `barber_db`.`services` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_staff_services_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `barber_db`.`staff` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
